### ISSUE TITLE
is trading added in game?

### ISSUE THREAD

**Issue by Toasted-1234** [ariajd27/elite-ce#2]
I fly and dock into planets but then how do i trade? i cant sell cargo because there is nothing there and when i look up tutorials the controls dont match (because its a calculator) thanks!

**Comment by ariajd27** [comment]
This is currently explained (albeit not permanently) in MANUAL.md. Pressing Yequ / Y= from the SHIP COMPUTER menu while docked at a station should take you to the MARKET LINK screen, which allows trading. Pressing Y= again should get you to OUTFITTING. Pressing GRAPH is the opposite of Y=. Also consider trying to press GRAPH while on the SHORT RANGE CHART screen; further right are the GALAXY CHART and the DATA ON SYSTEM screens. If any of this isn't working, please let me know!

**Comment by Toasted-1234** [comment]
Ok thanks! just one question on the game when I go to the sell materials nothing shows up how do I get stuff to sell?

**Comment by ariajd27** [comment]
Currently, the only way to obtain things to sell is to buy them. In future versions, I hope to adapt the salvage mechanic from the original onto the calculator.
